# Generated by Django 5.0.2 on 2024-02-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_cari', models.DateTimeField()),
                ('keyword', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('judul', models.CharField(max_length=200)),
                ('penulis', models.CharField(max_length=200)),
                ('penerbit', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=200)),
                ('tgl_terbit', models.DateField()),
                ('jumlah_halaman', models.CharField(max_length=200)),
                ('berat', models.CharField(max_length=200)),
                ('img_source', models.URLField()),
                ('rating', models.CharField(max_length=200)),
                ('cover', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
